[package]
name = "bn"
version = "0.4.3"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "Bramm, Georg <georg.bramm@aisec.fraunhofer.de>"]
description = "Pairing cryptography with the Barreto-Naehrig curve"
keywords = ["pairing","crypto","cryptography"]
readme = "README.md"
homepage = "https://github.com/georgbramm/bn"
repository = "https://github.com/georgbramm/bn"
license = "MIT OR Apache-2.0"

[[bench]]
name = "api"

[dependencies]
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
byteorder = "~0.5.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies.bincode]
version = "~0.6.0"
default-features = false
features = ["rustc-serialize"]
