[package]
name = "bn"
version = "0.4.5"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "Bramm, Georg <georg.bramm@aisec.fraunhofer.de>"]
description = "Pairing cryptography with the Barreto-Naehrig curve"
keywords = ["pairing","crypto","cryptography"]
readme = "README.md"
homepage = "https://github.com/georgbramm/bn"
repository = "https://github.com/georgbramm/bn"
license = "MIT OR Apache-2.0"

[[bench]]
name = "api"

[dependencies]
rand = "0.7.3"
byteorder = "1.2.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
arrayvec = "0.5.1"

[dev-dependencies.bincode]
version = "1.0.0"
default-features = false
